### ISSUE TITLE
Non-alphabet symbols

### ISSUE THREAD

**Issue by emmamack** [thearchitector/Mathematica-MATLAB#1]
Symbols in Mathematica currently become \["Symbol"] when run through Mathematica-MATLAB and copy/pasted to Matlab, which Matlab can't parse.

It would be helpful to change any non-alphabet symbols into something alphabetical (e.g. an alpha symbol could become "Alpha").

**Comment by thearchitector** [comment]
Thanks for letting me know, I hadn't thought of that. Will fix soon!

**Comment by thearchitector** [comment]
Resolved in https://github.com/thearchitector/Mathematica-MATLAB/commit/6a85e17eb844473e02c587f2e04eeb045258ffe6.
